In [ ]:
import torch
from torch import nn

In [ ]:
torch.__version__

'2.1.0+cu118'

In [ ]:
class ConvBlock(nn.Module):
    def __init__(self,
                in_channels,
                out_channels,
                use_activation=True,
                activation='relu',
                use_batchnorm=True,
                **kwargs,
                ):
        super().__init__()
        self.use_activation = use_activation
        self.cnn = nn.Conv2d(in_channels, out_channels, bias= not use_batchnorm, **kwargs)
        self.bn = nn.BatchNorm2d(out_channels) if use_batchnorm else nn.Identity()
        self.act = (
            nn.LeakyReLU(0.2, inplace=True)
            if activation == 'relu'
            else nn.PReLU(num_parameters=out_channels)
        )

    def forward(self, x):
      return self.act(self.bn(self.cnn(x))) if self.use_activation else self.bn(self.cnn(x))



In [ ]:
# Testing our conv block
import matplotlib.pyplot as plt

with torch.inference_mode():
    test_conv_block = ConvBlock(3, 64)
    random_image = torch.rand([1,3,4,4])

    output = test_conv_block(random_image)
    print(output[0,:3])
    print(output.shape)

tensor([[[-0.2281,  1.2712],
         [-0.1595,  0.6668]],

        [[-0.3048, -0.0020],
         [ 0.2676,  1.2666]],

        [[-0.1278,  1.3301],
         [-0.2470,  0.5439]]])
torch.Size([1, 64, 2, 2])


In [ ]:

class ResidualBlock(nn.Module):
    def __init__(self,
                 in_channels,
                 ):
        super().__init__()
        self.conv1 =  ConvBlock(in_channels, in_channels, True, 'PReLU',
                                use_batchnorm=True,
                                kernel_size=3,
                                stride=1,
                                padding=1)
        self.conv2 =  ConvBlock(in_channels, in_channels, False,
                                use_batchnorm=True,
                                kernel_size=3,
                                stride=1,
                                padding=1)

    def forward(self, x):
        out = self.conv1(x)
        out = self.conv2(x)
        # print(f"Input shape = {x.shape}, output shape = {out.shape}")
        # print(f"Output after convulation = {out[0,0]}")
        return out + x


In [ ]:
with torch.inference_mode():
    test_residual = ResidualBlock(3)
    input = torch.rand([1,3,5,5])
    print(input[:,0])
    output = test_residual(input)
    print(output[:,0])


tensor([[[0.8953, 0.8847, 0.5320, 0.2257, 0.4395],
         [0.0308, 0.2959, 0.5863, 0.3659, 0.4520],
         [0.1915, 0.5634, 0.7130, 0.3162, 0.4170],
         [0.3024, 0.3989, 0.8636, 0.6348, 0.5819],
         [0.1270, 0.7115, 0.5510, 0.4665, 0.3994]]])
tensor([[[-0.3286,  0.5078,  1.7625,  0.3210, -1.8076],
         [ 1.1032,  0.8129,  1.8206, -0.8152,  0.6572],
         [-0.9724,  0.0882,  1.5413, -0.2337, -0.3395],
         [-0.0113,  1.9144,  0.9283, -0.9011,  1.4417],
         [-0.5215,  2.0686,  1.7539,  0.6531,  0.5025]]])


In [ ]:
## Upsample Block

class UpsampleBlock(nn.Module):

    def __init__(self,
                 in_channels,
                 upscale_factor): # factor in 1 axis .
        super().__init__()
        self.conv = nn.Conv2d(in_channels, in_channels* upscale_factor**2, kernel_size = 3, stride = 1, padding=1)
        self.shuffle = nn.PixelShuffle(upscale_factor=upscale_factor)
        self.act = nn.PReLU(num_parameters=in_channels)

    def forward(self, x):
        # print(f"Tensor shape before Upsample = {x.shape} and after upsample it becomes = {self.shuffle(self.conv(x)).shape}")
        return self.shuffle(self.conv(x))



In [ ]:
# Testing the upsample block

with torch.inference_mode():
    upsampler = UpsampleBlock(4, 2)
    input = torch.rand([1,4,5,5])
    output= upsampler(input)
    print(f"Tensor shape before Upsample = {input.shape} and after upsample it becomes = {output.shape}")
    print(input[0,0])
    print(output[0,0])

In [ ]:
# Generator Class MAJOR CLASS

class Generator(nn.Module):

    def __init__(self,
                 num_channels=64,
                 num_blocks=16,
                 upscale_factor=2):
        super().__init__()
        self.initial = ConvBlock(3, num_channels,
                                 use_activation=True, activation= "PReLU",
                                 use_batchnorm=False,
                                 kernel_size=9, padding=4, stride=1)
        self.residuals = nn.Sequential(*[ResidualBlock(num_channels) for _ in range(num_blocks)] )
        self.mid_conv = ConvBlock(num_channels, num_channels, use_activation=False, use_batchnorm=True, kernel_size=3 , stride=1, padding=1)
        self.upsample = nn.Sequential(UpsampleBlock(num_channels, upscale_factor), UpsampleBlock(num_channels, upscale_factor))
        self.final_conv = nn.Conv2d(in_channels=num_channels, out_channels=3, kernel_size=9, stride= 1, padding=4)

    def forward(self, x):
        initial_out = self.initial(x)
        out = self.residuals(initial_out)
        out = self.mid_conv(out) + initial_out
        out = self.upsample(out)
        out = self.final_conv(out)
        return torch.tanh(out)




In [ ]:
# Testing our generator

with torch.inference_mode():
    gen = Generator()
    input = torch.rand([1,3,5,5])
    output = gen(input)
    # print(gen.state_dict())
    print(f"Shape of input = {input.shape}, and shape of output = {output.shape} ")

In [ ]:

# Diccriminator Major

class Discriminator(nn.Module):

    def __init__(self):
        super().__init__()
        channels = [64, 64, 128, 128, 256, 256, 512, 512]
        blocks = []
        for idx in range(len(channels)):
            blocks.append(
                ConvBlock(
                    in_channels = 3 if idx == 0 else channels[idx-1],
                    out_channels = channels[idx],
                    kernel_size = 3,
                    padding = 1,
                    stride = 1 + idx % 2,
                    use_batchnorm= False if idx == 0 else True
                )
            )
        self.conv_layers = nn.Sequential(*blocks)

        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool2d((6,6)),
            nn.Flatten(),
            nn.Linear(512*6*6, 1024),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Linear(1024, 1)
        )

    def forward(self, x):
        out = self.conv_layers(x)
        out = self.classifier(out)
        return out


In [ ]:

# testing disc

with torch.inference_mode():
    disc = Discriminator()
    x = torch.rand([5,3,400,300])
    out = disc(x)
    print(out.shape)

idx =  0
idx =  1
idx =  2
idx =  3
idx =  4
idx =  5
idx =  6
idx =  7
torch.Size([5, 1])
